EUCA-9103, EUCA-8924: Service registration CLIs
1. Old registration continues to work as before on both client and
   server side with the exception of --register-osg (below).
2. New registration CLI behaviour detailed below.
3. Service implementation details in the commits related to EUCA-8710.
 * Note: these changes are orthogonal to, so do not address, EUCA-7151
   and related deregistration issues.

- Adds --register-service [1].
- State [2] or registration [3] errors for any registered services are
  reported as part of the command output.
- The errors of other broken or notready services are also reported [4].
  This can be amended at will.
- Old style register-osg still works [5].
- Adds --deregister-service [6] continuing to preserve --deregister-osg
  [7]. Note: the deregister-osg command does not munge names and the
  right ones must be used based on the existing
- service configurations; this can be altered to be symmetric with the
  register-osg munging.
- Service configuration updates function as expected [8].
- Single register/deregister commands which can subsume all others [9].
  Exact same code paths as euca_conf --{register,deregister}-service.
- Describe service groups by partitions [10], tool implementations
  identify services, service groups and their members and all related
  characteristics using DescribeAvailableServiceTypes
  (see serviceregistration.py).
- Related human readable and comprehensive service availability and
  registration help computed based on system responses (as above; see
  DescribeAvailableServiceTypes) [11].
- Exposed error information for registration/deregistration [12].
- Simpler service error information from describe-services [13].  Old
  output (on stdout) remains unchanged, but could be easily pruned as it
  is largely subsumed by this output.

[1]  euca_conf --register-service -T user-api -H 10.111.1.66 -N API_66

[2]  Report of the objectstorage configuration error on first time configuration.
     ERROR  objectstorage       API_66      API_66.objectstorage   OSG object storage provider client not configured. Found property 'objectstorage.providerclient' empty or unset
manager(unset).  Legal values are: riakcs,ceph-rgw,walrus,s3

[3]  Duplicate configuration for a service which is part of the user-api service group.
     euca_conf --register-service -T tokens -H 10.111.1.66 -N API_66.tokens >/dev/null 2>&1;\
     euca_conf --register-service -T user-api -H 10.111.1.66 -N API_66
     error: registration failed
     ERROR  Registering  arn:euca:bootstrap:API_66:tokens:API_66.tokens/  failed because of  Component with name=API_66.tokens already exists with host=10.111.1.66

[4]  euca_conf --register-service -T user-api -H 10.111.1.66 -N API_66
     ERROR  cluster             PARTI00     CC_66                  java.net.ConnectException: Connection refused: /10.111.1.66:8774
     ...

[5]  euca_conf --register-osg --partition objectstorage --component OSG_66 --host 10.111.1.66
     Created new partition 'API_66'
     SERVICE  user-api            API_66      API_66                 http://10.111.1.66:8773/services/User-API  arn:euca:bootstrap:API_66:user-api:API_66/
     ...

[6]  euca_conf --deregister-service -T user-api -N API_66

[7]  euca_conf --deregister-osg  -P API_66 -C API_66

[8]  Change from host 10.111.1.66 to 10.111.1.71 for an already registered service:
     euca_conf --register-service -T user-api -H 10.111.1.71 -N API_66

[9]  Single register/deregister commands
     euca-register-service -T user-api -H 10.111.1.66 -P API_66 API_66
     euca-deregister-service API_66

[10] Describe a service group by using partitions
      euca-describe-services -P API_66

[11] euca_conf --register-service

    SERVICES
      The following commands are for registering specific services in Eucalyptus

      Eucalyptus       eucalyptus service implementation
                       euca_conf --register-service -T eucalyptus -N <NAME> -H <HOST>

      VMwareBroker     The VMware Broker service
                       euca_conf --register-service -T vmwarebroker -N <NAME> -H <HOST> -P <PARTITION>

      Arbitrator       The Arbitrator service
                       euca_conf --register-service -T arbitrator -N <NAME> -H <HOST> -P <PARTITION>

      Storage          The Storage Controller service
                       euca_conf --register-service -T storage -N <NAME> -H <HOST> -P <PARTITION>

      cluster          The Cluster Controller service
                       euca_conf --register-service -T cluster -N <NAME> -H <HOST> -P <PARTITION>

      WalrusBackend    The legacy Walrus Backend service
                       euca_conf --register-service -T walrusbackend -N <NAME> -H <HOST>

    SERVICE GROUPS
      The following commands are for registering service groups in Eucalyptus

      User-API         The service group of all user-facing API endpoint services
                       euca_conf --register-service -T user-api -N <NAME> -H <HOST>

                       This will register the following services:
                       Euare            IAM API service
                       CloudFormation   Cloudformation API service
                       Compute          the Eucalyptus EC2 API service
                       CloudWatch       CloudWatch API service
                       ObjectStorage    S3 API service
                       Tokens           STS API service
                       LoadBalancing    ELB API service
                       AutoScaling      Auto Scaling API service

[12] euca_conf --deregister-service -T user-api -N API_66
     error: deregistration failed
     ERROR  Failed to deregister user-api: API_66 because of : Failed to lookup any registered component with the name: API_66

[13] euca-describe-services -E >/dev/null
     ERROR  loadbalancingbackend  eucalyptus  10.111.1.66            ColocationBootstrapper.enable( ): failed because of: The loadbalancingbackend service depends upon a locally ENABLED
eucalyptus, terminating bootstrap for component: loadbalancingbackend
     ERROR  loadbalancingbackend  eucalyptus  10.111.1.66            ERR-1014 2014-04-23 13:42:31 Load balancer image not configured.  LoadBalancing service will not be available.
     ERROR  loadbalancingbackend  eucalyptus  10.111.1.66            LoadBalancingPropertyBootstrapper.enable( ): returned false, terminating bootstrap for component: loadbalancingbackend
     ERROR  imaging             eucalyptus  10.111.1.66            ERR-1015 2014-04-23 13:42:31 Imaging worker image not configured.  Imaging service will not be available.
     ERROR  imaging             eucalyptus  10.111.1.66            ImagingServicePropertyBootstrapper.enable( ): returned false, terminating bootstrap for component: imaging